"""M10 鉴权与用户管理（L7 横切；ADR-007、§3 M10、REQ-M10-F01..F05）。

**两条鉴权路径，同一身份源（SSH 公钥）**：

* **agent 路径**（CLI/HTTP）：每请求 SSHSIG 签名 → :func:`verify_signature`
  （载荷含 RAW_PATH + query，S2；nonce 仅在验签通过后入库，S7）；
* **WebUI 路径**（浏览器）：挑战-响应登录换会话 Cookie → :func:`resolve_session`
  （S8：``JOIN users.status='active'``；S13：库内只存 ``SHA256(token)``）。

**授权**：四角色硬上限 + 文档集级 grant 收窄（:func:`authorize`，S5 形式化）。

**审计**：用户/密钥/授权变更与鉴权失败落 ``events``（``entity='auth'``，S1）；
失败事件 ``actor='anonymous'`` 且自述身份只进 ``claimed_*``（S10）。

用法（M06/M07）：

.. code-block:: python

    from agenticdocer.auth import AuthContext, require_auth, require_permission, write_context

    @app.get("/api/v1/docs")
    async def list_docs(ctx: AuthContext = Depends(require_permission("read"))): ...
"""

from __future__ import annotations

from .bootstrap import admin_pubkey_file, admin_username, bootstrap_admin, has_active_admin
from .errors import (
    AUTH_REJECTED_CODE,
    BOOTSTRAP_HINT,
    AuthError,
    AuthenticationError,
    BootstrapError,
    RateLimitError,
    SignatureFormatError,
    SignatureVerificationError,
)
from .middleware import (
    EXEMPT_PATHS,
    EXEMPT_PREFIXES,
    KEY_ID_HEADER,
    NONCE_HEADER,
    SESSION_COOKIE_NAME,
    SIGNATURE_HEADER,
    TIMESTAMP_HEADER,
    AuthContext,
    SshSigHeaders,
    check_timestamp,
    clear_session_cookie,
    client_ip,
    cookie_secure,
    current_context,
    is_exempt,
    normalize_path,
    parse_timestamp,
    raw_path,
    require_auth,
    require_permission,
    resolve_request_identity,
    session_cookie_kwargs,
    set_session_cookie,
    verify_signature,
    write_context,
)
from .rbac import (
    GRANT_PERMISSIONS,
    GRANT_SCOPES,
    MANAGE_USERS,
    PERMISSIONS,
    PERMISSION_IMPLIES,
    ROLE_PERMISSIONS,
    applicable_grants,
    authorize,
    grant_matches,
    grant_target_matches,
    role_permits,
    validate_grant,
)
from .sessions import (
    CHALLENGE_TTL_SECONDS,
    Challenge,
    LoginResult,
    PurgeReport,
    check_rate_limit,
    consume_nonce,
    create_challenge,
    future_skew_seconds,
    login,
    logout,
    nonce_ttl_seconds,
    purge_expired,
    rate_limit_per_min,
    reset_rate_limits,
    resolve_session,
    session_token_hash,
    session_ttl_seconds,
    signature_max_skew_seconds,
)
from .signing import (
    KEY_ID_PREFIX,
    SigningError,
    build_sshsig,
    default_key_path,
    fingerprint,
    key_type_for,
    load_private_key,
    login_payload,
    new_nonce,
    normalize_key_id,
    public_key_line,
    request_payload,
    sign_message,
    sign_message_armored,
    sign_request_headers,
    timestamp_now,
)
from .sshsig import (
    MAGIC,
    MIN_RSA_BITS,
    NAMESPACE,
    RECOMMENDED_RSA_BITS,
    SUPPORTED_KEY_TYPES,
    PublicKeyInfo,
    SshSig,
    armor,
    dearmor,
    parse_sshsig,
    validate_public_key,
    verify_sshsig,
)
from .users import (
    DEFAULT_ADMIN_USERNAME,
    add_ssh_key,
    authorize_user,
    count_active_admins,
    create_grant,
    create_user,
    delete_grant,
    delete_user,
    find_active_key,
    find_user_by_username,
    get_user,
    list_grants,
    list_ssh_keys,
    list_users,
    load_grants,
    log_auth_event,
    log_auth_failure,
    revoke_ssh_key,
    update_user,
)

__all__ = [
    # 常量与错误
    "AUTH_REJECTED_CODE",
    "BOOTSTRAP_HINT",
    "CHALLENGE_TTL_SECONDS",
    "DEFAULT_ADMIN_USERNAME",
    "EXEMPT_PATHS",
    "EXEMPT_PREFIXES",
    "GRANT_PERMISSIONS",
    "GRANT_SCOPES",
    "KEY_ID_HEADER",
    "KEY_ID_PREFIX",
    "MAGIC",
    "MANAGE_USERS",
    "MIN_RSA_BITS",
    "NAMESPACE",
    "NONCE_HEADER",
    "PERMISSIONS",
    "PERMISSION_IMPLIES",
    "RECOMMENDED_RSA_BITS",
    "ROLE_PERMISSIONS",
    "SESSION_COOKIE_NAME",
    "SIGNATURE_HEADER",
    "SUPPORTED_KEY_TYPES",
    "TIMESTAMP_HEADER",
    "AuthContext",
    "AuthError",
    "AuthenticationError",
    "BootstrapError",
    "Challenge",
    "LoginResult",
    "PublicKeyInfo",
    "PurgeReport",
    "RateLimitError",
    "SignatureFormatError",
    "SignatureVerificationError",
    "SigningError",
    "SshKey",
    "SshSig",
    "SshSigHeaders",
    # 签名（agent 路径）
    "verify_signature",
    "verify_sshsig",
    "parse_sshsig",
    "dearmor",
    "armor",
    "validate_public_key",
    "build_sshsig",
    "sign_message",
    "sign_message_armored",
    "sign_request_headers",
    "request_payload",
    "login_payload",
    "fingerprint",
    "key_type_for",
    "normalize_key_id",
    "load_private_key",
    "public_key_line",
    "default_key_path",
    "new_nonce",
    "timestamp_now",
    # 会话（WebUI 路径）
    "create_challenge",
    "login",
    "logout",
    "resolve_session",
    "resolve_request_identity",
    "purge_expired",
    "consume_nonce",
    "session_token_hash",
    "session_ttl_seconds",
    "nonce_ttl_seconds",
    "signature_max_skew_seconds",
    "future_skew_seconds",
    "challenge_ttl_seconds",
    "rate_limit_per_min",
    "check_rate_limit",
    "reset_rate_limits",
    # FastAPI 依赖
    "require_auth",
    "require_permission",
    "current_context",
    "write_context",
    "is_exempt",
    "normalize_path",
    "raw_path",
    "client_ip",
    "parse_timestamp",
    "check_timestamp",
    "cookie_secure",
    "session_cookie_kwargs",
    "set_session_cookie",
    "clear_session_cookie",
    # RBAC
    "ROLE_PERMISSIONS",
    "role_permits",
    "grant_matches",
    "grant_target_matches",
    "applicable_grants",
    "authorize",
    "authorize_user",
    "validate_grant",
    # 用户与授权管理
    "list_users",
    "get_user",
    "create_user",
    "update_user",
    "delete_user",
    "find_user_by_username",
    "count_active_admins",
    "add_ssh_key",
    "revoke_ssh_key",
    "find_active_key",
    "list_ssh_keys",
    "list_grants",
    "load_grants",
    "create_grant",
    "delete_grant",
    "log_auth_event",
    "log_auth_failure",
    # 自举
    "bootstrap_admin",
    "has_active_admin",
    "admin_pubkey_file",
    "admin_username",
]

from .sessions import challenge_ttl_seconds  # noqa: E402 - 已在 __all__ 中声明
from agenticdocer.model import SshKey  # noqa: E402 - 便捷再导出（M06/M07 常用）
